// Stream the large experiment key instead of copying it through WASM's memory.
// The envelope is generated by ledger-v9; only its three SCALE byte vectors are
// streamed. Small payloads are checked byte-for-byte against the ledger encoder.
import { strict as assert } from 'node:assert';
import { createReadStream, statSync } from 'node:fs';
import { request } from 'node:http';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { createProvingPayload } from '@midnightntwrk/ledger-v9';

export const vectorLength = (n: number): Buffer => {
  assert.ok(Number.isSafeInteger(n) && n >= 0 && n <= 0xffffffff);
  if (n < 64) return Buffer.from([n * 4]);
  if (n < 16384) { const out = Buffer.alloc(2); out.writeUInt16LE(n * 4 + 1); return out; }
  if (n < 2 ** 30) { const out = Buffer.alloc(4); out.writeUInt32LE(n * 4 + 2); return out; }
  const out = Buffer.alloc(5); out[0] = 3; out.writeUInt32LE(n, 1); return out;
};

function envelope(preimage: Uint8Array, binding: bigint | undefined) {
  const material = { proverKey: new Uint8Array(), verifierKey: new Uint8Array(), ir: new Uint8Array() };
  const empty = Buffer.from(createProvingPayload(preimage, undefined, material));
  assert.deepEqual(empty.subarray(-5), Buffer.from([1, 0, 0, 0, 0]));
  // Field elements use variable-size encoding too; let the ledger encode the
  // optional binding rather than assuming a 32-byte scalar representation.
  const withBinding = Buffer.from(createProvingPayload(preimage, binding, material));
  assert.deepEqual(withBinding.subarray(0, empty.length - 1), empty.subarray(0, -1));
  return { prefix: empty.subarray(0, -4), suffix: withBinding.subarray(empty.length - 1) };
}

export function checkStreamingEncoding(preimage: Uint8Array) {
  for (const size of [0, 1, 63, 64, 16383, 16384, 65536]) {
    for (const binding of [undefined, 123n]) {
      const parts = [Buffer.alloc(size, 31), Buffer.from([41, 42]), Buffer.from([51])];
      const { prefix, suffix } = envelope(preimage, binding);
      assert.deepEqual(Buffer.concat([prefix, ...parts.flatMap(p => [vectorLength(p.length), p]), suffix]),
        Buffer.from(createProvingPayload(preimage, binding, { proverKey: parts[0], verifierKey: parts[1], ir: parts[2] })));
    }
  }
}

export async function proveStream(baseUrl: string, preimage: Uint8Array, binding: bigint | undefined, files: string[]) {
  assert.equal(files.length, 3);
  const url = new URL('/prove', baseUrl);
  assert.equal(url.protocol, 'http:', 'isolated local proof server only');
  assert.ok(['127.0.0.1', 'localhost', '[::1]'].includes(url.hostname), 'proof inputs must stay local');
  const { prefix, suffix } = envelope(preimage, binding);
  const sizes = files.map(file => statSync(file).size);
  const contentLength = prefix.length + suffix.length + sizes.reduce((sum, n) => sum + vectorLength(n).length + n, 0);
  async function* chunks() {
    yield prefix;
    for (const [i, file] of files.entries()) {
      yield vectorLength(sizes[i]);
      yield* createReadStream(file);
    }
    yield suffix;
  }
  const start = performance.now();
  const response = await new Promise<Buffer>((resolve, reject) => {
    const req = request(url, { method: 'POST', headers: {
      'content-type': 'application/octet-stream', 'content-length': contentLength,
    } }, res => {
      const received: Buffer[] = [];
      res.on('data', chunk => received.push(chunk));
      res.on('error', reject);
      res.on('end', () => {
        const body = Buffer.concat(received);
        if (res.statusCode !== 200) reject(new Error(`proof server ${res.statusCode}: ${body.toString().slice(0, 3000)}`));
        else resolve(body);
      });
    });
    req.setTimeout(25 * 60_000, () => req.destroy(new Error('proof server timeout')));
    req.on('error', reject);
    pipeline(Readable.from(chunks()), req).catch(reject);
  });
  return { proof: new Uint8Array(response), milliseconds: performance.now() - start, requestBytes: contentLength };
}
