------------------------------------------------------------------------
-- Midnight.Passport.Compiler
--
-- Emits Julia source code that reconstructs a HomTerm directly via
-- Catlab's symmetric-monoidal combinators.  The FreeStrictMonoidal
-- HomTerm maps onto Catlab one-to-one:
--
--   gen n A B   ↦  gen("n", [A…], [B…])        (singleton_diagram ∘ Box)
--   idm A       ↦  id(Ports([A…]))
--   f >> g      ↦  compose(⟦f⟧, ⟦g⟧)
--   f ⊗  g      ↦  otimes(⟦f⟧, ⟦g⟧)
--
-- Because compose/otimes wire positionally (Catlab checks arity, not
-- port names), the emitted program reproduces the strict-SMC semantics
-- exactly — including channels whose names repeat across parallel lanes,
-- which the older name-keyed JSON flattener mis-routed.
--
-- emitTerm lives inside an
--   opaque unfolding ObjTerm _⊗₀_ unit Var
-- block so the library's opaque ObjTerm is transparent as List String,
-- exposing each generator's domain/codomain channel names.
------------------------------------------------------------------------

module Midnight.Passport.Compiler where

open import Data.String as S using (String)
open import Data.List   as L using (List; []; _∷_; map)

open import Midnight.Passport.FMTerm

infixr 5 _⟨++⟩_
_⟨++⟩_ : String → String → String
_⟨++⟩_ = S._++_

------------------------------------------------------------------------
-- 0.  String utilities
------------------------------------------------------------------------

quoted : String → String
quoted s = "\"" ⟨++⟩ s ⟨++⟩ "\""

commas : List String → String
commas []           = ""
commas (x ∷ [])     = x
commas (x ∷ y ∷ zs) = x ⟨++⟩ ", " ⟨++⟩ commas (y ∷ zs)

-- A Julia Vector{String} literal.  The empty case must be typed as
-- String[] so Box infers Vector{String} rather than Vector{Any}.
juliaStringArray : List String → String
juliaStringArray []           = "String[]"
juliaStringArray (x ∷ xs)     = "[" ⟨++⟩ commas (map quoted (x ∷ xs)) ⟨++⟩ "]"

------------------------------------------------------------------------
-- 1.  Term emission (inside opaque unfolding)
------------------------------------------------------------------------

opaque
  unfolding ObjTerm _⊗₀_ unit Var

  -- Emit a HomTerm as a Catlab combinator expression.  The implicit
  -- indices A (domain) and B (codomain) unfold to List String, giving
  -- each generator its port-name lists.
  emitTerm : ∀ {A B} → HomTerm A B → String

  emitTerm {A} {B} (var ℓ) =
    "gen(" ⟨++⟩ quoted (Label.name ℓ) ⟨++⟩ ", "
          ⟨++⟩ juliaStringArray A ⟨++⟩ ", "
          ⟨++⟩ juliaStringArray B ⟨++⟩ ")"

  emitTerm {A} id =
    "id(Ports(" ⟨++⟩ juliaStringArray A ⟨++⟩ "))"

  -- _∘_ is right-to-left; the right arg (f) runs first, so it is the
  -- left operand of Catlab's left-to-right compose.
  emitTerm (g ∘ f) =
    "compose(" ⟨++⟩ emitTerm f ⟨++⟩ ", " ⟨++⟩ emitTerm g ⟨++⟩ ")"

  emitTerm (f ⊗₁ g) =
    "otimes(" ⟨++⟩ emitTerm f ⟨++⟩ ", " ⟨++⟩ emitTerm g ⟨++⟩ ")"

  -- Symmetry and the coherence isomorphisms are identity-on-the-nose in
  -- the strict SMC; emit an identity on the domain.  None of the current
  -- diagrams use a non-trivial σ, so the lost permutation is immaterial
  -- (a genuine braid would need the tensor split, which the flattened
  -- channel list does not carry).
  emitTerm {A} σ  = "id(Ports(" ⟨++⟩ juliaStringArray A ⟨++⟩ "))"
  emitTerm {A} λ⇒ = "id(Ports(" ⟨++⟩ juliaStringArray A ⟨++⟩ "))"
  emitTerm {A} λ⇐ = "id(Ports(" ⟨++⟩ juliaStringArray A ⟨++⟩ "))"
  emitTerm {A} ρ⇒ = "id(Ports(" ⟨++⟩ juliaStringArray A ⟨++⟩ "))"
  emitTerm {A} ρ⇐ = "id(Ports(" ⟨++⟩ juliaStringArray A ⟨++⟩ "))"
  emitTerm {A} α⇒ = "id(Ports(" ⟨++⟩ juliaStringArray A ⟨++⟩ "))"
  emitTerm {A} α⇐ = "id(Ports(" ⟨++⟩ juliaStringArray A ⟨++⟩ "))"

------------------------------------------------------------------------
-- 2.  Public entry points
------------------------------------------------------------------------

-- A single "name" => <expr> entry for the DIAGRAMS vector.
compileNamedDiagram : ∀ {A B} → String → HomTerm A B → String
compileNamedDiagram n t =
  "  " ⟨++⟩ quoted n ⟨++⟩ " => " ⟨++⟩ emitTerm t

-- Wrap a comma-separated body of named entries into a complete,
-- self-contained Julia source file binding `DIAGRAMS`.
wrapJuliaDiagrams : String → String
wrapJuliaDiagrams body =
  "# GENERATED by the Agda compiler (Midnight.Passport.Compiler).\n"
    ⟨++⟩ "# Do not edit; regenerate from the HomTerm sources.\n\n"
    ⟨++⟩ "using Catlab\n"
    ⟨++⟩ "using Catlab.WiringDiagrams\n"
    ⟨++⟩ "using Catlab.Theories\n\n"
    ⟨++⟩ "gen(name, ins, outs) = singleton_diagram(Box(name, ins, outs))\n\n"
    ⟨++⟩ "DIAGRAMS = [\n"
    ⟨++⟩ body ⟨++⟩ "\n"
    ⟨++⟩ "]\n"
