------------------------------------------------------------------------
-- Midnight.Passport.Semantics
--
-- Attaches semantics to the architecture diagram via the standard
-- "free category + interpretation functors" recipe.
--
--   * C_arch — the free strict symmetric monoidal category whose ONLY
--     morphism generators are the boxes appearing in `architecture`
--     (the enumerated `ArchBox`).  `architectureᶜ` is the architecture
--     rebuilt in this category.
--
--   * Syntax interpretation — a structure-preserving map
--     `C_arch → FMTerm` sending each `ArchBox` to its named `gen`.  It
--     shares the object language with FMTerm, so it is the identity on
--     objects and recovers the current `architecture` term verbatim.
--
--   * Semantics interpretation — the generator data mapping each channel
--     to a `Channel` and each `ArchBox` to a `Machine`.  By the universal
--     property of the free SMC this data INDUCES a (symmetric monoidal)
--     functor `C_arch → Machine` once the Machine category is packaged as
--     such; until then we record the generator maps.  The per-box
--     machines are stubs for now.
------------------------------------------------------------------------

module Midnight.Passport.Semantics where

open import Data.String using (String)
open import Data.List   using (List; []; _∷_)
open import Data.Unit   using (⊤)

open import Categories.FreeMonoidal using (Symm; _≤_; v≤v)

import Midnight.Passport.FMTerm as FM
open FM.H using (ObjTerm; _⊗₀_; unit; Var)      -- the shared object language

import CategoricalCrypto.Channel.Core as Ch
import CategoricalCrypto.Machine.Core as Mc

------------------------------------------------------------------------
-- 1.  Morphism generators: exactly the boxes of `architecture`
------------------------------------------------------------------------

data ArchBox : ObjTerm → ObjTerm → Set where
  didContract     : ArchBox unit (Var "TBD")
  nameService     : ArchBox unit (Var "TBD")
  peerDevices     : ArchBox unit (Var "TBD SYNC")
  recoveryHelpers : ArchBox unit (Var "RECOVERY-P5")
  indexer         : ArchBox unit (Var "READ STATE")
  accountCustody  : ArchBox (Var "TBD" ⊗₀ Var "TBD") (Var "JUBJUB SCHNORR")
  localWallet     : ArchBox (Var "TBD SYNC") (Var "STATE")
  proofServer     : ArchBox unit (Var "WITNESS-IPC")
  passportKey     : ArchBox
                      ( Var "RECOVERY-P5" ⊗₀ Var "READ STATE" ⊗₀ Var "JUBJUB SCHNORR"
                      ⊗₀ Var "STATE" ⊗₀ Var "WITNESS-IPC" )
                      ( Var "User" )

-- The free strict SMC generated by ArchBox.
module D = FM.H.Mor ArchBox
open D using (HomTerm; var; id; _∘_; _⊗₁_; σ; λ⇒; λ⇐; ρ⇒; ρ⇐; α⇒; α⇐)

-- Convenience constructors (mirroring FMTerm).
infixr 9 _>>_
_>>_ : ∀ {A B C} → HomTerm A B → HomTerm B C → HomTerm A C
f >> g = g ∘ f

infixr 8 _⊗_
_⊗_ : ∀ {A B C E} → HomTerm A B → HomTerm C E → HomTerm (A ⊗₀ C) (B ⊗₀ E)
_⊗_ = _⊗₁_

idm : (a : ObjTerm) → HomTerm a a
idm _ = id

------------------------------------------------------------------------
-- 2.  `architecture`, rebuilt in C_arch
------------------------------------------------------------------------

opaque
  unfolding ObjTerm _⊗₀_ unit Var

  architectureᶜ : HomTerm unit (Var "User")
  architectureᶜ =
    ( var didContract ⊗ var nameService ⊗ var peerDevices )
    >>
    ( var recoveryHelpers ⊗ var indexer ⊗ var accountCustody
    ⊗ var localWallet ⊗ var proofServer
    )
    >>
    var passportKey

------------------------------------------------------------------------
-- 3.  Syntax interpretation  C_arch → FMTerm
--
-- Identity on objects (shared object language); each generator maps to
-- its named `gen`.
------------------------------------------------------------------------

synBox : ∀ {A B} → ArchBox A B → FM.HomTerm A B
synBox didContract     = FM.gen "Midnight DID contract"   unit (Var "TBD")
synBox nameService     = FM.gen "Name Service"            unit (Var "TBD")
synBox peerDevices     = FM.gen "+ peer devices"          unit (Var "TBD SYNC")
synBox recoveryHelpers = FM.gen "Recovery helpers"        unit (Var "RECOVERY-P5")
synBox indexer         = FM.gen "Indexer"                 unit (Var "READ STATE")
synBox accountCustody  = FM.gen "Account custody contract"
                           (Var "TBD" ⊗₀ Var "TBD") (Var "JUBJUB SCHNORR")
synBox localWallet     = FM.gen "Local wallet storage"    (Var "TBD SYNC") (Var "STATE")
synBox proofServer     = FM.gen "Proof server"            unit (Var "WITNESS-IPC")
synBox passportKey     = FM.gen "Passport Key"
                           ( Var "RECOVERY-P5" ⊗₀ Var "READ STATE" ⊗₀ Var "JUBJUB SCHNORR"
                           ⊗₀ Var "STATE" ⊗₀ Var "WITNESS-IPC" )
                           ( Var "User" )

syn : ∀ {A B} → HomTerm A B → FM.HomTerm A B
syn (var b)   = synBox b
syn id        = FM.id
syn (g ∘ f)   = syn g FM.∘ syn f
syn (f ⊗₁ g)  = syn f FM.⊗₁ syn g
syn λ⇒        = FM.λ⇒
syn λ⇐        = FM.λ⇐
syn ρ⇒        = FM.ρ⇒
syn ρ⇐        = FM.ρ⇐
syn α⇒        = FM.α⇒
syn α⇐        = FM.α⇐
syn (σ ⦃ i ⦄) = FM.σ ⦃ i ⦄

-- The architecture diagram in the FMTerm world, obtained functorially.
architectureˢ : FM.HomTerm unit (Var "User")
architectureˢ = syn architectureᶜ

------------------------------------------------------------------------
-- 4.  Semantics interpretation: generators → Machine
--
-- This is the universal-property data (object map + morphism map). Once
-- `Machine` is packaged as a symmetric monoidal category it induces the
-- semantics functor C_arch → Machine. Stubs for now.
------------------------------------------------------------------------

-- Placeholder channel for every architecture channel.
● : Ch.Channel
● = ⊤ Ch.⇿ ⊤

objₘ : String → Ch.Channel
objₘ _ = ●

-- Object-term interpretation (monoid hom on the nose for the generators;
-- the coherence fix-ups for arbitrary terms are what the induced functor
-- supplies once Machine is a packaged SMC).
opaque
  unfolding ObjTerm _⊗₀_ unit Var

  ⟦_⟧₀ : ObjTerm → Ch.Channel
  ⟦ []     ⟧₀ = Ch.I
  ⟦ x ∷ xs ⟧₀ = objₘ x Ch.⊗₀ ⟦ xs ⟧₀

-- The chaotic stub machine: every transition is permitted.
stub : ∀ {A B} → Mc.Machine A B
stub = Mc.MkMachine {State = ⊤} (λ _ _ _ _ → ⊤)

-- Morphism-generator interpretation.
morₘ : ∀ {A B} → ArchBox A B → Mc.Machine ⟦ A ⟧₀ ⟦ B ⟧₀
morₘ _ = stub

------------------------------------------------------------------------
-- 5.  Validation: the syntax functor recovers `architecture` verbatim
------------------------------------------------------------------------

import Midnight.Passport.Architecture as A
open import Relation.Binary.PropositionalEquality using (_≡_; refl)

opaque
  unfolding ObjTerm _⊗₀_ unit Var architectureᶜ A.architecture

  syn-recovers-architecture : architectureˢ ≡ A.architecture
  syn-recovers-architecture = refl
