------------------------------------------------------------------------
-- Midnight.Passport.Semantics
--
-- Attaches semantics to the architecture diagram via the standard
-- "free category + interpretation functors" recipe.
--
--   * C_arch — the free strict symmetric monoidal category generated by
--     the channels `ArchChan` (objects) and the boxes `ArchBox`
--     (morphisms) of `architecture`.  `architectureᶜ` is the architecture
--     rebuilt in this category.
--
--   * Syntax functor `syn : C_arch → FMTerm` — the object generator map
--     `chanName : ArchChan → String` together with `synBox` sending each
--     box to its named `gen`.  Since the objects differ (ArchChan vs
--     String) `syn` transports along `chanName` on the nose; it recovers
--     the current `architecture` term verbatim.
--
--   * Semantics generator data — each channel to a `Channel`, each
--     `ArchBox` to a `Machine`.  By the universal property of the free
--     SMC this data INDUCES a symmetric monoidal functor C_arch → Machine
--     once the Machine category is packaged as such.  Stubs for now.
------------------------------------------------------------------------

module Midnight.Passport.Semantics where

open import Data.String using (String)
open import Data.List   using (List; []; _∷_; map; _++_)
open import Data.List.Properties using (map-++)
open import Data.Unit   using (⊤)
open import Relation.Binary.PropositionalEquality using (_≡_; refl)

open import Categories.FreeMonoidal using (Symm; _≤_; v≤v)
import Categories.FreeStrictMonoidal as FSM

import Midnight.Passport.FMTerm as FM

import CategoricalCrypto.Channel.Core as Ch
import CategoricalCrypto.Machine.Core as Mc

------------------------------------------------------------------------
-- 0.  Object generators: the architecture's channels
------------------------------------------------------------------------

data ArchChan : Set where
  TBD TBD-SYNC RECOVERY-P5 READ-STATE JUBJUB-SCHNORR STATE WITNESS-IPC User : ArchChan

-- The free strict SMC's object language is built over ArchChan.
module HA = FSM.FreeMonoidalHelper Symm ArchChan
open HA using (ObjTerm; _⊗₀_; unit; Var)

------------------------------------------------------------------------
-- 1.  Morphism generators: exactly the boxes of `architecture`
------------------------------------------------------------------------

data ArchBox : ObjTerm → ObjTerm → Set where
  didContract     : ArchBox unit (Var TBD)
  nameService     : ArchBox unit (Var TBD)
  peerDevices     : ArchBox unit (Var TBD-SYNC)
  recoveryHelpers : ArchBox unit (Var RECOVERY-P5)
  indexer         : ArchBox unit (Var READ-STATE)
  accountCustody  : ArchBox (Var TBD ⊗₀ Var TBD) (Var JUBJUB-SCHNORR)
  localWallet     : ArchBox (Var TBD-SYNC) (Var STATE)
  proofServer     : ArchBox unit (Var WITNESS-IPC)
  passportKey     : ArchBox
                      ( Var RECOVERY-P5 ⊗₀ Var READ-STATE ⊗₀ Var JUBJUB-SCHNORR
                      ⊗₀ Var STATE ⊗₀ Var WITNESS-IPC )
                      ( Var User )

-- The free strict SMC generated by ArchChan & ArchBox.
open HA.Mor ArchBox

------------------------------------------------------------------------
-- 2.  `architecture`, rebuilt in C_arch
------------------------------------------------------------------------

opaque
  unfolding ObjTerm _⊗₀_ unit Var

  architectureᶜ : HomTerm unit (Var User)
  architectureᶜ =
    ((var passportKey)
    ∘
    ( var recoveryHelpers ⊗₁ var indexer ⊗₁ var accountCustody
    ⊗₁ var localWallet ⊗₁ var proofServer
    ))
    ∘
    ( var didContract ⊗₁ var nameService ⊗₁ var peerDevices )

------------------------------------------------------------------------
-- 3.  Syntax functor  C_arch → FMTerm
--
-- Object map `chanName`; morphism map `synBox`.  `syn` transports the
-- object indices through `chanName` (a monoid hom over ++, hence the
-- `map-++` rewrites).
------------------------------------------------------------------------

chanName : ArchChan → String
chanName TBD            = "TBD"
chanName TBD-SYNC       = "TBD SYNC"
chanName RECOVERY-P5    = "RECOVERY-P5"
chanName READ-STATE     = "READ STATE"
chanName JUBJUB-SCHNORR = "JUBJUB SCHNORR"
chanName STATE          = "STATE"
chanName WITNESS-IPC    = "WITNESS-IPC"
chanName User           = "User"

opaque
  unfolding ObjTerm _⊗₀_ unit Var

  -- Object part of the functor: ArchChan-terms ↦ String-terms.
  Φ : ObjTerm → FM.ObjTerm
  Φ = map chanName

  synBox : ∀ {A B} → ArchBox A B → FM.HomTerm (Φ A) (Φ B)
  synBox didContract     = FM.gen "Midnight DID contract"   FM.unit (FM.Var "TBD")
  synBox nameService     = FM.gen "Name Service"            FM.unit (FM.Var "TBD")
  synBox peerDevices     = FM.gen "+ peer devices"          FM.unit (FM.Var "TBD SYNC")
  synBox recoveryHelpers = FM.gen "Recovery helpers"        FM.unit (FM.Var "RECOVERY-P5")
  synBox indexer         = FM.gen "Indexer"                 FM.unit (FM.Var "READ STATE")
  synBox accountCustody  = FM.gen "Account custody contract"
                             (FM.Var "TBD" FM.⊗₀ FM.Var "TBD") (FM.Var "JUBJUB SCHNORR")
  synBox localWallet     = FM.gen "Local wallet storage"    (FM.Var "TBD SYNC") (FM.Var "STATE")
  synBox proofServer     = FM.gen "Proof server"            FM.unit (FM.Var "WITNESS-IPC")
  synBox passportKey     = FM.gen "Passport Key"
                             ( FM.Var "RECOVERY-P5" FM.⊗₀ FM.Var "READ STATE" FM.⊗₀ FM.Var "JUBJUB SCHNORR"
                             FM.⊗₀ FM.Var "STATE" FM.⊗₀ FM.Var "WITNESS-IPC" )
                             ( FM.Var "User" )

  syn : ∀ {A B} → HomTerm A B → FM.HomTerm (Φ A) (Φ B)
  syn (var b)                  = synBox b
  syn id                       = FM.id
  syn (g ∘ f)                  = syn g FM.∘ syn f
  syn (_⊗₁_ {A} {B} {C} {D} f g)
    rewrite map-++ chanName A C | map-++ chanName B D = syn f FM.⊗₁ syn g
  syn λ⇒                       = FM.λ⇒
  syn λ⇐                       = FM.λ⇐
  syn (ρ⇒ {A}) rewrite map-++ chanName A [] = FM.ρ⇒
  syn (ρ⇐ {A}) rewrite map-++ chanName A [] = FM.ρ⇐
  syn (α⇒ {A} {B} {C})
    rewrite map-++ chanName (A ⊗₀ B) C | map-++ chanName A B
          | map-++ chanName A (B ⊗₀ C) | map-++ chanName B C = FM.α⇒ {Φ A} {Φ B} {Φ C}
  syn (α⇐ {A} {B} {C})
    rewrite map-++ chanName A (B ⊗₀ C) | map-++ chanName B C
          | map-++ chanName (A ⊗₀ B) C | map-++ chanName A B = FM.α⇐ {Φ A} {Φ B} {Φ C}
  syn (σ {A} {B} ⦃ i ⦄)
    rewrite map-++ chanName A B | map-++ chanName B A = FM.σ {Φ A} {Φ B} ⦃ i ⦄

-- Validation: the syntax functor recovers `architecture` verbatim.
import Midnight.Passport.Architecture as A

opaque
  unfolding ObjTerm _⊗₀_ unit Var Φ synBox syn architectureᶜ A.architecture

  -- The architecture diagram in the FMTerm world, obtained functorially.
  -- `syn architectureᶜ` lands in FM.HomTerm (Φ unit) (Φ (Var User)); since
  -- Φ unit = FM.unit and Φ (Var User) = FM.Var "User" definitionally, we
  -- give it the FMTerm-native type, the same one `architecture` has.
  architectureˢ : FM.HomTerm FM.unit (FM.Var "User")
  architectureˢ = syn architectureᶜ

  syn-recovers-architecture : architectureˢ ≡ A.architecture
  syn-recovers-architecture = refl

------------------------------------------------------------------------
-- 4.  Semantics interpretation: generators → Machine
------------------------------------------------------------------------

-- Placeholder channel for every architecture channel.
● : Ch.Channel
● = ⊤ Ch.⇿ ⊤

objₘ : ArchChan → Ch.Channel
objₘ _ = ●

opaque
  unfolding ObjTerm _⊗₀_ unit Var

  ⟦_⟧₀ : ObjTerm → Ch.Channel
  ⟦ []     ⟧₀ = Ch.I
  ⟦ x ∷ xs ⟧₀ = objₘ x Ch.⊗₀ ⟦ xs ⟧₀

-- The chaotic stub machine: every transition is permitted.
stub : ∀ {A B} → Mc.Machine A B
stub = Mc.MkMachine {State = ⊤} (λ _ _ _ _ → ⊤)

-- Morphism-generator interpretation.
morₘ : ∀ {A B} → ArchBox A B → Mc.Machine ⟦ A ⟧₀ ⟦ B ⟧₀
morₘ _ = stub
